### ISSUE TITLE
Issues about Download ready-to-use index and annotator files

### ISSUE THREAD

**Issue by tjhwangxiong** [salzmanlab/SICILIAN#12]
Dear [roozbehdn](https://github.com/roozbehdn)

When I downloaded `Human`: https://drive.google.com/file/d/1cGfn7MZbGewBJp6ZGGW_IOW3nWEAHOPz/view?usp=sharing

I failed when 99% was downloaded, and GOOGLE shuted down this link showing:

`Too many users have viewed or downloaded this file recently`

So Can we download this file and the corresponding `Mouse` somewhere else?

**Comment by roozbehdn** [comment]
This happens when a large file gets downloaded many times in a short period of time. If you try downloading at a later time, the issue should be gone. We tried and could download the files from google drive. But just in case we have also uploaded the reference/index files to zenodo and you can download them from there as well: 
mouse files: https://doi.org/10.5281/zenodo.6462332
human files: https://doi.org/10.5281/zenodo.6462314

**Comment by tjhwangxiong** [comment]
> This happens when a large file gets downloaded many times in a short period of time. If you try downloading at a later time, the issue should be gone. We tried and could download the files from google drive. But just in case we have also uploaded the reference/index files to zenodo and you can download them from there as well: mouse files: [https://doi.org/10.5281/zenodo.6462332 ](https://doi.org/10.5281/zenodo.6462332) human files: [https://doi.org/10.5281/zenodo.6462314 ](https://doi.org/10.5281/zenodo.6462314)

Thanks a lot. I have now succedded.
