### ISSUE TITLE
A TypeError

### ISSUE THREAD

**Issue by houruiyan** [salzmanlab/SICILIAN#6]
Hi, thank you for this great tools. I meet some trouble when I run this application. 

![image](https://user-images.githubusercontent.com/56068158/135802305-028fc7e1-c4a1-41b0-b622-c44b4bfe81c8.png)

I think my configuration for the SICILIAN is correct. 
![image](https://user-images.githubusercontent.com/56068158/135802450-7f73c45d-483f-410f-ab23-2b598ba4a6ee.png)

Hope to get your reply. Thank you.

**Comment by roozbehdn** [comment]
Hi Ruiyan,

Your input parameters all look good. I think the issue is with jobs submissions. There is a function `sbatch_file` in SICILIAN.py script that submits SICILIAN jobs using `sbatch` command to the slurm job scheduler. Have you modified it based on the job scheduler that you have access to on your server? You should modify it depending based on how you can sbatch your jobs on your server. Please let mw know if you have any questions or issues with modifying the snatch_file function.
