### ISSUE TITLE
Error submitting job

### ISSUE THREAD

**Issue by MEFarhadieh** [salzmanlab/SICILIAN#8]
Dear Sicilian team and dear dr. Dehghannasiri @roozbehdn ,
Thank you for developing this great tool.
I ran `python SICILIAN.py` and got below error:

<img width="1292" alt="Screen Shot 1400-12-05 at 12 13 56 PM" src="https://user-images.githubusercontent.com/100343349/155489716-9e92c5a4-c585-4212-abc0-b5a133b1d739.png">

I just modified `sbatch_file` at line 130 in `SICILIAN.py` based on my cluster resources and didn't change definition `sbatch_file` at beginning.
So what should I do?
Thanks so much for the help.

**Comment by roozbehdn** [comment]
Hi, the script is based on python/3.6.1. What version of python are you using?
Also, you should use `python3 SICILIAN.py`.
Also, have you set the toggles correctly? if you run for 10x data, you should set both `run_whitelist` and `run_extract` to `True`.

**Comment by MEFarhadieh** [comment]
Thank you so much for your quick answer. I use python 3.9.7 as python default. Also, I modified `SICILIAN.py ` inputs and toggles as README description. 

![image](https://user-images.githubusercontent.com/100343349/155679931-dc145e14-8cb7-4728-857b-c255096db852.png)

Additionally, I find that this error due to slurm (I'm so sorry for my last comment). So I reinstalled slurm and then got the below error

<img width="1440" alt="Screen Shot 1400-12-06 at 9 12 43 AM" src="https://user-images.githubusercontent.com/100343349/155681649-d02b3224-5466-4045-b098-ccca7f59325d.png">

and now I have `run_whitelist.sh` file on cluster 

<img width="1440" alt="Screen Shot 1400-12-06 at 9 28 08 AM" src="https://user-images.githubusercontent.com/100343349/155682514-e45849aa-06a4-4902-b810-c32ea587f24c.png">

I think I should setting up slurm.conf file or try each section manually.

**Comment by roozbehdn** [comment]
I think the issue is that the `def sbatch_file(file_name,out_path, name, job_name, time, mem, command, dep="", dep_type = "afterok"):` section is not compatible with your cluster setting and you should modify it in your SICILIAN.py script. This command makes the sbatch files for each step of sicilian which then will be submitted to the cluster queue as jobs.

`sbatch_file` function should be modified based on your cluster settings for job submission. Based on your run_whitelist.sh screenshot, the first change that I see is:  `#SBATCH -p horence,owners,quake` (these are the queues that we are using on our own cluster). You should change it based on your queue. So for example, if you use queue `X` for your jobs, then that line should be changed to `job_file.write("#SBATCH -p X\n")` (assuming that you can define the queue on your cluster with a -p flag)

**Comment by MEFarhadieh** [comment]
Thank you so much for your help. 
Unfortunately, my cluster doesn't compatible with Slurm. So, I changed `def sbatch_file()` to make a bash file which is not use `#SBATCH`. After this my problem is disappeared.

**Comment by wook2014** [comment]
I meet a similar problem and the question for me is in SICILIAN.py line136
```
def submit_job(file_name):
  """Submit sbatch job to cluster"""
  status, job_num = subprocess.getstatusoutput("sbatch {}".format(file_name))
```
change "sbatch {}" to "bash {}" works for me
